Shorter SCSP behaviour review duration
Informo/specs pull request #4
Opened 2018-11-02 21:35 UTC by GordonF42

Since we are early in development and there will be a lot of SCSP for adding new features, which may also depend on other SCSP. The current 2-week review duration will probably slow down a bit too much the initial development process.
The review duration will probably be restored to 2 weeks when the ground work is finished.

Note: Specs bot will need to be updated to display 7 days instead of 14 when this is merged.

2018-11-02 22:04 UTC, vabd requested changes
On top of that, please expand each line to as close to 80 char as possible (while keeping it under or equal to this length) to keep the formatting consistent trough the whole documentation.

FTR this would turn the end of the file into:

```
total of 7 days (one week). During this period, anyone **can** issue a review on
the SCS or comment and discuss it, preferably in the pull request's comments.
```

2018-11-02 22:04 UTC, vabd commented on content/introduction/scsp.md
> +total of 7 days (one weeks). During this period, anyone **can** issue a
```suggestion
total of 7 days (one week). During this period, anyone **can** issue a
```

2018-11-02 23:09 UTC, GordonF42 commented
my bad, should be good now

2018-11-03 10:20 UTC, vabd approved these changes
lgtm, let's wait till the end of the 14 day-long call for review before merging it

2018-11-16 11:19 UTC, vabd commented
Merging today. Might be worth noting that this new rule only applies for SCSs that have been open after the merging happens (the ones that have been open before that are still subject to the full 14 days rule).

2018-11-16 11:20 UTC, merged